### ISSUE TITLE
Bug in cache

### ISSUE THREAD

**Issue by prologic** [jointwt/twtxt#369]
Seeing this for the first time, _probaby_ an edge case with the cache:

```
twtxt_twtxt.1.z00i8z8ro5ei@dm4.mills.io    | panic: runtime error: invalid memory address or nil pointer dereference
twtxt_twtxt.1.z00i8z8ro5ei@dm4.mills.io    | [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xcf4b87]
twtxt_twtxt.1.z00i8z8ro5ei@dm4.mills.io    |
twtxt_twtxt.1.z00i8z8ro5ei@dm4.mills.io    | goroutine 1192 [running]:
twtxt_twtxt.1.z00i8z8ro5ei@dm4.mills.io    | github.com/jointwt/twtxt/internal.(*Cache).FetchTwts.func2(0xc004ea6780, 0xc0008088d0, 0xc000679a70, 0xc0000da000, 0xc000296810, 0xc0007b89c0, 0x111c7c0, 0xc00019c870, 0xc004db5df6, 0x3, ...)
twtxt_twtxt.1.z00i8z8ro5ei@dm4.mills.io    | 	/src/internal/cache.go:320 +0x5a7
twtxt_twtxt.1.z00i8z8ro5ei@dm4.mills.io    | created by github.com/jointwt/twtxt/internal.(*Cache).FetchTwts
twtxt_twtxt.1.z00i8z8ro5ei@dm4.mills.io    | 	/src/internal/cache.go:188 +0x2dd
```

**Comment by JonLundy** [comment]
https://github.com/jointwt/twtxt/blob/master/internal/cache.go#L320

looks like the map key isnt set.. probably should guard that with a 

```go

if feed, ok :=  cache.Twts[feed.URL]; ok { twts = feed.Twts }
```

**Comment by jlj77** [comment]
I think I'm having the same problem; potential relevant section of syslog:
```
Jan 26 20:53:27 <hostname> twtd[71986]: time="2021-01-26T20:53:27Z" level=error msg="feed for news changed from http://twt.nfld.uk/user/news/twtxt.txt to https://twt.nfld.uk/user/news/twtxt.txt" error="<nil>"
Jan 26 20:53:27 <hostname> twtd[71986]: panic: runtime error: invalid memory address or nil pointer dereference
Jan 26 20:53:27 <hostname> twtd[71986]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xcf4a27]
Jan 26 20:53:27 <hostname> twtd[71986]: goroutine 195 [running]:
Jan 26 20:53:27 <hostname> twtd[71986]: github.com/jointwt/twtxt/internal.(*Cache).FetchTwts.func2(0xc00065de60, 0xc0006aa680, 0xc0003a55c0, 0xc000124b40, 0xc000214a80, 0xc0002523c0, 0x111a740, 0xc0003d18f0, 0xc00086bca0, 0x4, ...)
Jan 26 20:53:27 <hostname> twtd[71986]:       /home/jj/Projects/git/twtxt/internal/cache.go:320 +0x5a7
Jan 26 20:53:27 <hostname> twtd[71986]: created by github.com/jointwt/twtxt/internal.(*Cache).FetchTwts
Jan 26 20:53:27 <hostname> twtd[71986]:       /home/jj/Projects/git/twtxt/internal/cache.go:188 +0x2dd
Jan 26 20:53:27 <hostname> systemd[1]: twtd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```

**Comment by thewismit** [comment]
I believe I've hit the same bug
```
goroutine 9026 [running]:
github.com/jointwt/twtxt/internal.(*Cache).FetchTwts.func2(0xc000ebe480, 0xc000c9e670, 0xc0017bb2c0, 0xc0000b2240, 0xc0001d9bf0, 0xc000996420, 0x111c7c0, 0xc000065cc0, 0xc000cad860, 0x3, ...)
        /src/internal/cache.go:320 +0x5a7
created by github.com/jointwt/twtxt/internal.(*Cache).FetchTwts
        /src/internal/cache.go:188 +0x2dd
```

**Comment by prologic** [comment]
@JonLundy Got a PR in mind?

**Comment by prologic** [comment]
Yeah I'm looking at the code on my laptop on the bus now and this should
Be impossible 😳

**Comment by JonLundy** [comment]
@prologic  it probably has something to do with the feed changing url code
so it sees feed changed but not modified since X. its looking for the old/new? feed cache and its not there, probably new

so.. gotta be copy the old feed cache to the new one so its there

https://github.com/jointwt/twtxt/blob/master/internal/cache.go#L247-L251
